import enum

class ENUM_TRADE_REQUEST_ACTIONS(enum.Enum):
    TRADE_ACTION_DEAL = 0
    TRADE_ACTION_PENDING = 1
    TRADE_ACTION_SLTP = 2
    TRADE_ACTION_MODIFY = 3
    TRADE_ACTION_REMOVE = 4
    TRADE_ACTION_CLOSE_BY = 5

class ENUM_ORDER_TYPE(enum.Enum):
    ORDER_TYPE_BUY = 0
    ORDER_TYPE_SELL = 1
    ORDER_TYPE_BUY_LIMIT = 2
    ORDER_TYPE_SELL_LIMIT = 3
    ORDER_TYPE_BUY_STOP = 4
    ORDER_TYPE_SELL_STOP = 5
    ORDER_TYPE_BUY_STOP_LIMIT = 6
    ORDER_TYPE_SELL_STOP_LIMIT = 7
    ORDER_TYPE_CLOSE_BY = 8

class ORDER_TYPE_FILLING(enum.Enum):
    ORDER_FILLING_FOK = 0
    ORDER_FILLING_IOC = 1
    ORDER_FILLING_BOC = 2
    ORDER_FILLING_RETURN = 3

class ENUM_ORDER_TYPE_TIME(enum.Enum):
    ORDER_TIME_GTC = 0
    ORDER_TIME_DAY = 1
    ORDER_TIME_SPECIFIED = 2
    ORDER_TIME_SPECIFIED_DAY = 3

class ENUM_ORDER_REASON(enum.Enum):
    ORDER_REASON_CLIENT  = 0
    ORDER_REASON_MOBILE  = 1
    ORDER_REASON_WEB     = 2
    ORDER_REASON_EXPERT  = 3
    ORDER_REASON_SL      = 4
    ORDER_REASON_TP      = 5
    ORDER_REASON_SO      = 6

class ENUM_SERVER_RETURN_CODES(enum.Enum):
    TRADE_RETCODE_REQUOTE = 10004
    TRADE_RETCODE_REJECT =  10006
    TRADE_RETCODE_DONE = 10009

class ENUM_DEAL_ENTRY(enum.Enum):
    DEAL_ENTRY_IN = 0
    DEAL_ENTRY_OUT = 1
    DEAL_ENTRY_INOUT = 2
    DEAL_ENTRY_OUT_BY   = 3

